# Generated by Django 4.1.7 on 2023-05-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('man_date', models.DateField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='pro_image')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Cloath', 'Cloath'), ('Cosmetics', 'Cos')], max_length=100)),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
