# Generated by Django 4.1.7 on 2023-05-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='man_date',
            field=models.DateField(auto_now=True),
        ),
    ]
