# Generated by Django 4.1.7 on 2023-05-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_mng_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Std_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('std', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
