# Generated by Django 4.1.7 on 2023-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mng_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=100)),
                ('img', models.ImageField(null=True, upload_to='profile_pics')),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
