# Generated by Django 4.1.7 on 2023-05-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_mng_model_delete_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mng_model',
            old_name='img',
            new_name='image',
        ),
    ]
