# Generated by Django 4.1.7 on 2023-05-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_std_model_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_model',
            name='std',
            field=models.IntegerField(verbose_name='Standard'),
        ),
    ]
