# Generated by Django 4.1.7 on 2023-05-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_img_mng_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mng_model',
            name='image',
        ),
    ]
