# Generated by Django 4.1.7 on 2023-05-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_mng_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mng_model',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
