# Generated by Django 4.1.7 on 2023-05-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_std_model_std'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Std_model',
        ),
        migrations.AlterField(
            model_name='mng_model',
            name='age',
            field=models.IntegerField(db_column='Age'),
        ),
        migrations.AlterField(
            model_name='mng_model',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
