# Generated by Django 4.1.7 on 2023-05-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_std_model_alter_mng_model_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mng_model',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
