# Generated by Django 4.1.7 on 2023-05-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
