# Generated by Django 4.1.7 on 2023-05-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_tch_model_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tch_model',
            name='div',
            field=models.CharField(choices=[('A', '1'), ('B', '2'), ('C', '3')], max_length=100, verbose_name='division'),
        ),
    ]
