# Generated by Django 4.1.7 on 2023-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_tch_model_div'),
    ]

    operations = [
        migrations.CreateModel(
            name='Std_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('std', models.IntegerField(verbose_name='Standard')),
                ('div', models.CharField(choices=[('A', '1'), ('B', '2'), ('C', '3')], max_length=100, verbose_name='Division')),
                ('DOJ', models.DateField(help_text='mm/dd/yyyy', verbose_name='date of joining')),
                ('image', models.ImageField(upload_to='Std_pics/')),
                ('cv', models.FileField(db_column='Resume', upload_to='Std_cvs/')),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.DeleteModel(
            name='Tch_model',
        ),
    ]
